# .travis.yml file
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

notifications:
  email:
    recipients:
      - messmerd97@gmail.com 
    on_success: always  # default: change 
    on_failure: always # default: always

script: "python simple_tests.py"
